// Dynamic LaTeX / Overleaf Resume Generator Utility

export function generateTailoredLatex(candidateName, jobTitle, targetCompany, keySkills = [], missingKeywords = []) {
  const skillsFormatted = keySkills.join(", ");
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' });

  return `% Autogenerated ATS-Optimized Overleaf LaTeX Resume
% Candidate: ${candidateName}
% Target Role: ${jobTitle} @ ${targetCompany}
% Generated Date: ${dateStr}

\\documentclass[letterpaper,11pt]{article}
\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}

\\pagestyle{fancy}
\\fancyhf{} 
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.0in}
\\addtolength{\\topmargin}{-0.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Section formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\vline height 1.5pt width \\textwidth \\vspace{-5pt}]

\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Huge \\scshape ${candidateName}} \\\\ \\vspace{2pt}
    \\small Senior Full Stack \\& Cloud Security Engineer $|$ ${jobTitle} Specialist \\\\
    \\small Bengaluru, India $|$ \\href{mailto:rapuruprasanthi@gmail.com}{rapuruprasanthi@gmail.com} $|$ +91 98765 43210 $|$ \\href{https://github.com/rapuruprasanthi}{github.com/rapuruprasanthi}
\\end{center}

%-----------SUMMARY-----------
\\section{Executive Summary}
Accomplished Full Stack Engineer with 5+ years of experience designing secure, high-concurrency cloud applications, automated microservice pipelines, and custom AI agent workflows. Customized specifically for the \\textbf{${jobTitle}} role at \\textbf{${targetCompany}}, emphasizing expertise in \\textbf{${skillsFormatted}}.

%-----------SKILLS-----------
\\section{Core Competencies \\& Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     \\textbf{Primary Stack}{: ${skillsFormatted}, TypeScript, Node.js, Python, FastAPI, Docker} \\\\
     \\textbf{Cloud \\& Security}{: AWS IAM, Kubernetes, Cloud Security, JWT Authentication, OAuth2, Zero-Trust Architecture} \\\\
     \\textbf{Emphasized Keywords}{: ${missingKeywords.length > 0 ? missingKeywords.join(", ") : "REST, GraphQL, Continuous Integration"}} \\\\
     \\textbf{Tools \\& Platforms}{: Overleaf, LaTeX, Git, CI/CD Actions, Linux, PostgreSQL, Vector Search}
    }}
 \\end{itemize}

%-----------EXPERIENCE-----------
\\section{Professional Experience}
  \\begin{itemize}[leftmargin=0.15in, label={}]
    \\item
      \\begin{tabularx}{\\textwidth}{X r}
        \\textbf{Senior Lead Engineer} & 2023 -- Present \\\\
        \\textit{Apex Tech Solutions} & Bengaluru, IN \\\\
      \\end{tabularx}
      \\begin{itemize}
        \\item Designed autonomous career application agent with dynamic Overleaf LaTeX resume compilation engine.
        \\item Integrated JWT authentication microservices and role-based access control (RBAC) securing API endpoints.
        \\item Optimized multi-portal job discovery and automated cold email outreach pipelines, driving a +28.4\\% recruiter conversion rate.
      \\end{itemize}
  \\end{itemize}

\\end{document}
`;
}
